---

- hosts: all
  become: true
  gather_facts: no
  tasks:

  -  name: "Waiting for hosts to come online"
     wait_for:
       port: 22
       host: "{{ inventory_hostname }}"
     delegate_to: localhost

- hosts: all
  become: true
  roles:
    - base

- hosts: master
  become: true
  roles:
    - master
