- name: Copy custom script to home directory
  copy:
    src: files/join_kube_2.sh
    dest: /home/debian/join_kube_2.sh
    owner: debian
    group: debian
    mode: '0744'

- name: Execute shell script for Kubernetes
  script: join_kube_2.sh
  register: outputShell4

- debug: var=outputShell4.stdout_lines
